[package]
name = "utils"
version.workspace = true
edition.workspace = true

[features]
testing = []

[dependencies]
indexmap.workspace = true
itertools.workspace = true

[dev-dependencies]
env_logger.workspace = true
test-case.workspace = true
test-log.workspace = true
