[package]
name = "syntax_codegen"
version.workspace = true
edition.workspace = true

[package.metadata.cargo-udeps.ignore]
normal = ["syntax"]

[[bin]]
name = "generate_syntax"
path = "src/bin/generate_syntax.rs"

[dependencies]
genco.workspace = true
xshell.workspace = true

[dev-dependencies]
env_logger.workspace = true
test-log.workspace = true
